### ISSUE TITLE
Pass query parameters to redirect helper

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#143]
If we want to pass query params to the redirect helper it looks like that currently:

`$this->redirect('comments/create?someId=123&someAnimal=hase');`

We want the signature to look like this:

`$this->redirect('comments/create', ['someId' => 123, 'someAnimal' => 'hase']);`

Please write tests and adapt the abstract `Controller` class accordingly.

**Comment by SharktheFire** [comment]
Implemented in #199
