### ISSUE TITLE
Tom and Hauke should have access to Papertrail and Mailgun data

### ISSUE THREAD

**Issue by SharktheFire** [Jimdo/reportbook#204]

**Comment by Partyschaum** [comment]
Go to @isprunk and ask him to give you a mail address for the "Azubi Team". Maybe `team-azubi@jimdo.com` or something. Then use this address for Services you use in your team and have one place to store those credentials.

This place should be LastPass™️ . So ask @isprunk also for LastPass access. Create a "Team Azubi" there also and put all the credentials there.

  - [ ] Get `team-azubi@jimdo.com` from @isprunk 
  - [ ] Configure this address for all used services (e.g. Mailgun, Papertrail)
  - [ ] Get LastPass™️ access from @isprunk 
  - [ ] Create a group (or whatever this concept is called in LastPass™️) for you team
  - [ ] Put credentials there
  - [ ] Give @Jimdo/azubis access to this group

**Comment by SharktheFire** [comment]
- [ ] same with mlab service

**Comment by SharktheFire** [comment]
done 🤓
