### ISSUE TITLE
Make Mailgun configurable

### ISSUE THREAD

**Issue by SharktheFire** [Jimdo/reportbook#205]

**Comment by tomstich** [comment]
Live version is not working.
The environment variables arent working in wonderland.
```Uncaught MongoDB\Driver\Exception\AuthenticationException: Authentication failed```

**Comment by SharktheFire** [comment]
Live version still not working..

**Comment by SharktheFire** [comment]
# PMA (Post Mortem Analysis)

## The problem
Cannot connect to the online version https://reportbook.jimdo-platform.net.
Authentication failed.
## What was affected and what was the impact
Wrong mongo password for the mlab database was setting in the wonderland credentials.
And the authentication for the login with the username 'reportbook' failed.
## Solution
Set new mongo password in the wonderland credentials for the login in the mlab database.
