### ISSUE TITLE
Store the passwords in a secure manner

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#223]
In order to prevent the leakage of clear text passwords we want the user's password to be salted [in a secure manner](https://crackstation.net/hashing-security.htm).

**Be aware of the fact that you have a running service out there! By just changing the password encryption strategy you will break your live service! Hence you will also need a migration strategy in place!**

  - [x] Think of possible migration strategies and list them here for discussion

Currently you store the passwords in clear text. Since you want a new **strategy** for treating passwords do the following:

  - [x] Create an `Password` interface with `encrypt(string $password): string`, `verify(string $password, string $hash): bool`
  - [x] Extract your current "clear text" strategy into a `ClearTextPassword` class which implements `Password`
  - [x] Implement a `SaltedPassword` class which implements `Password` with a strategy from the linked document above
  - [x] Use the `ClearTextPassword` strategy in your application. This *must not* affect the current behaviour

**Comment by SharktheFire** [comment]
We could check at the login if the user object contains a salt. If not, we can add a salt, hash the current password and save it to the database

**Comment by SharktheFire** [comment]
Why should the function decrypt return a string? We think that it is not possible to decrypt to password. We could check if given password matches the saved password from the user and return a boolean. Are we wrong?

**Comment by tomstich** [comment]
What should the functions `encrypt` and `decrypt` do in the `ClearTextPassword`? 
The class is only for clear text passwords, right?

**Comment by SharktheFire** [comment]
Should pass the functions `encrypt` and `decrypt` in the `ClearTextPassword` only the password to the functions in the `SaltedPassword` class??
