### ISSUE TITLE
Make validation accessible through base controller class

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#25]
I want access to the validation incorporated into the abstract `Controller` class.

It should be used as follows in the subclassed controller:

```
class MyController extends Controller
{
    public function someAction()
    {
        $this->addRequestValidation('xxx', 'string');
        $this->addRequestValidation('yyy', 'int');

        if ($this->isRequestValid()) {
            // some code
        }
    }
}
```

So you'll need to implement `addRequestValidation()` and `isRequestValid()` on the `Controller` class. Do this please by writing the corresponding tests beforehand. 😀

**Comment by tomstich** [comment]
Implemented in #24
