### ISSUE TITLE
Annual Survery View for Reports of Trainee

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#254]
In order to have a pain free survey over a trainee's reports we need a annual survey. In this survey the trainer or admin sees the following information for each week:
  - `approval requested` (eingereicht) in *yellow*
  - `report disapproved` (abgelehnt) in *red*
  - `no report for this week` (noch kein Bericht) in *white*
  - `report approved` (genehmigt) in *green*

See the attached sketch:
![img_3514](https://cloud.githubusercontent.com/assets/626843/20838909/d803c55e-b8aa-11e6-846d-28c855cf7421.jpeg)

**Comment by tomstich** [comment]
Implemented in #276
