### ISSUE TITLE
Add Fixed Width To Report View

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#258]
![zeilenumbruche in reports](https://cloud.githubusercontent.com/assets/626843/21052499/ab2c83ba-be25-11e6-9c35-ee26a3ad9774.png)

The text can't be read if it's too long. It's unwieldy to mark the text and "scroll to the right" just to be able to read the report.

Please add a max width to the report view.

**Comment by tomstich** [comment]
Implemented in #268
