### ISSUE TITLE
Fix messed up formatting of reports

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#329]
![screenshot 2017-02-20 11 14 51](https://cloud.githubusercontent.com/assets/626843/23120762/f40dd068-f75d-11e6-8999-9d85c0e9ec7e.png)

Maybe after the introduction of TWIG templates you somehow messed up the formatting or applied a filter which removes it?

Please fix this since the reports aren't readable at the moment.

**Comment by SharktheFire** [comment]
Implemented in #332

**Comment by SharktheFire** [comment]
Implemented in #338
