### ISSUE TITLE
Create a Sequence Diagram of Report Creation

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#347]
Fist make yourself familiar with [Sequence Diagrams](https://www.google.de/search?q=call+sequence+diagram). Then I want you to use your debugging environment to step through the whole sequence of creating a new report. Examine and note down all the parts of the application which are involved with this request.

Use the [Web Sequence Diagrams Tool](https://www.websequencediagrams.com/) to create the diagram. Tip: Register there to be able to save your work.

**Comment by SharktheFire** [comment]
[https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgVGhlIHdob2xlIHNlcXVlbmNlIG9mIGNyZWF0aW5nIGEgcmVwb3J0Cgpyb3V0ZXItPlIAAwU6IGluc3RhbmNlIAALBgoKABMGABcKZGlzcGF0Y2ggdXJpABMLAEoFQ29udHJvbGwAOw4ADA8KCgAdCjwAJhRleHRlbmRzIAAnDABQEC0-Tm90aWZpY2F0aW9uU2VydmljZQCBMwsACxMAMRRBcHBsACsZAAsSCgoAHxItPitTZXJpYWxpegCCNAwKAAsKLT4tAFQUcmV0dXJuCgoAgTYTLT5QYXBlcnRyYWlsU3Vic2NyaWJlcjogcmVnaXN0ZXIgUGFwdAAPEQA0Fk1haWxndW4AMhUACxEAg10Sc3RhcnRTZXNzaW9uAINyGgCEVAVlIEFjdGlvbgCDGhQAhA4SY2FsbAAxBwAGMWlzVHJhaW5lZQCEQAwtPitSZXF1ZXN0OiBnZXQgcwCBLwZEYXRhCgASBy0tPi0AhRgMAIJ9BgAdDQBZLABoB1ZhbGlkAIUPFCsAhEsUAIIlBgCGKgYAhDkXAIZHBmJvb2sAHxcAEBEALAlNb25nb1JlcG9zaXRvcnkAZwgAhjkIABAPAGMJAIceEQCGagctLT4tAIc6BwBJEQCCNgcAgQYOAFARAIB_GGFsbCBzYXZlAIEAGQCGSQxzAIZZCACBFggAhlILLT4tAIEDHgA0CWQAgQ0eAEAJAIJsDQCBURUAgm0NAIh0FW5vdGlmeSBldmVuAIMbFQCHdx0gUmVhZG9ubHkAhAsbAIFuCQCFPRMALxAAhmskcmVkaXJlY3QgdG8gbGlzdCBhAIdECACMEg9yZW5kZXIgUmVzcG9uc2VPYmplY3QAjB0KAIxKBgCEEwsAIQYKCgoKCgoAAQU&s=modern-blue](url)
