### ISSUE TITLE
Setup Debugging Environment

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#348]
In order to have proper debugging support in you PHP development environment accomplish the following steps:

- [x] Look at #340 and understand the changes I made there
- [x] Write down the explanation of what those changes are doing in the comments below
- [x] Merge #340 
- [x] Download [Visual Studio Code](https://www.google.de/search?q=visual+studio+code)
- [x] Install the *PHP Debug* and the *PHP IntelliSense* extension in VS Code
- [x] Configure the correct `localSourceRoot` and `serverSourceRoot` mapping for your code for the *PHP Debug* extension
- [x] Install the [XDebug Helper](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc) into your Chrome browser
- [x] Build the development container with `make build-debug`
- [x] Start the PHP Application (Because of step 2 you understand what happens now 😸 )

Now you should be able to set breakpoints in the VS Code editor. Set some. The `router.php` could be a good starting point since this is code which is always executed.

Start the debugger and enable the xdebug session in the Chrome browser via the *XDebug Helper*.

Your requests should now be catched by the debugger session in the editor! 🚀 

Play around with the debugger. Step through the code and have fun and gather understanding about your code. 😄 

Then continue happily with #347! :1st_place_medal:

**Comment by Partyschaum** [comment]
Where is the textual explanation from the 2nd step:

- [ ] Write down the explanation of what those changes are doing in the comments below

**Comment by SharktheFire** [comment]
You can see this in #340.
