### ISSUE TITLE
Report status set back to 'edited' after editing a 'disapproved' report

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#37]
Currently `DISAPPROVED` reports "vanish" of the trainers report overview if they get edited afterwards. I want `DISAPPROVED` reports still to be editable of course. After saving a disapproved report it should have `REVISED` as new status. Such `REVISED` reports can be edited like new reports. They also can get requested for approval again and having their status then set to `APPROVAL_REQUESTED` again.

And those `REVISED` reports should be listed in the trainer's overview.

**Comment by tomstich** [comment]
Implemented in #30
