### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#406]
Please update the `README.md` with the latest setup instructions.

- What are the prerequisites? (e.g. docker, docker-compose, etc.)
- Which steps to perform to in which order to get the system
  - started
  - stoped
  - updated
  - run tests (all, or single ones)
- How to do troubleshooting?
  - How to handle which kind of errors? (e.g., check your `.env`, remove volumes, etc)

The above is a non exhaustive list. If you can think of additional topics feel free to add them to the `README.md`.

**Comment by tomstich** [comment]
Implemented in #426
