### ISSUE TITLE
Setup Frontendtesting Capabilities with PHP-Webdriver

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#434]
- [x] Configure [php-webdriver](https://github.com/facebook/php-webdriver) in your test suite with the help of [this blog article](http://codeception.com/11-12-2013/working-with-phpunit-and-selenium-webdriver.html).
 - [x] Write a frontend integration test for the profile image upload.
 - [x] Get this setup running on Circle CI

**Comment by tomstich** [comment]
Configure and Setup on Circle Ci refers on #438

**Comment by tomstich** [comment]
Integration test for profile image upload refers on #441
