### ISSUE TITLE
Build Url Helper

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#456]
I just found some broken link tags. For example: https://github.com/Jimdo/reportbook/blob/master/src/Web/Controller/Views/UserlistView.html#L22

Build a url view helper which looks like this:

```
goto('controllername', 'action', 'some linktext', [ 'baz' => 'bam', 'foo' => 'bar' ])
```

This should generate output like:
`<a href="/controllername/action?baz=bam&foo=bar">some linktext</a>`

The query parameters should be optional.

**Comment by tomstich** [comment]
Implemented in #461
