### ISSUE TITLE
Cannot access to reportbook in web => Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by SharktheFire** [Jimdo/reportbook#516]
If I try to reach https://berichtsheft.io I got this message

```Fatal error: Uncaught Error: Class 'Jimdo\Reports\Web\Controller\NotificationService' not found in /var/www/src/Web/Controller/UserController.php:65 Stack trace: #0 /var/www/src/Web/Router.php(179): Jimdo\Reports\Web\Controller\UserController->__construct(Object(Jimdo\Reports\Web\Request), Object(Jimdo\Reports\Web\RequestValidator), Object(Jimdo\Reports\Web\ApplicationConfig), Object(Jimdo\Reports\Web\Response), Object(Twig_Environment)) #1 /var/www/src/Web/Router.php(114): Jimdo\Reports\Web\Router->createController('user') #2 /var/www/app/router.php(15): Jimdo\Reports\Web\Router->dispatch('/user') #3 {main} thrown in /var/www/src/Web/Controller/UserController.php on line 65```

**Comment by tomstich** [comment]
Implemented in #517
