### ISSUE TITLE
"Nächsten Bericht anzeigen" funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#586]
**Was passiert:**

Ich wähle "Nächsten Bericht anzeigen" aus und nach dem "genehmigen" eines Berichts bekomme ich einen (gefühlt) zufälligen. Teilweise sogar nicht von dem Auszubildenden den ich zuvor in der Kalenderansicht ausgewählt hatte.

**Was ich erwarte:**

Ich wähle "Nächsten Bericht anzeigen" aus und bekomme den zeitlich nächstfolgenden Bericht.

**Comment by tomstich** [comment]
Implemented in #588
